# Generated by Django 4.1 on 2023-10-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='reduced_title',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
