# Generated by Django 4.1 on 2023-10-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0002_section_reduced_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
