# Generated by Django 4.1 on 2023-10-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0004_resumesection_section_number_resumeentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='reduced_title',
            new_name='short_title',
        ),
    ]
