# Generated by Django 4.1 on 2023-10-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0008_publicationssection_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='short_title',
            field=models.CharField(default='None', max_length=15),
        ),
    ]
