# Generated by Django 4.1 on 2023-10-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0009_alter_section_short_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.CharField(max_length=50)),
                ('secondary_text', models.CharField(max_length=100)),
            ],
        ),
    ]
