# Generated by Django 4.1 on 2023-10-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0011_publication_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='fowardbuttons')),
            ],
        ),
    ]
