# Generated by Django 4.1 on 2023-10-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0012_sitebutton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebutton',
            name='icon',
            field=models.ImageField(upload_to='sitebuttons'),
        ),
    ]
