# Generated by Django 4.1 on 2023-10-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0013_alter_sitebutton_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebutton',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
