# Generated by Django 4.1 on 2023-10-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0014_sitebutton_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebutton',
            name='icon',
            field=models.FileField(upload_to='sitebuttons'),
        ),
    ]
