# Generated by Django 4.1 on 2023-10-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0015_alter_sitebutton_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsection',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
