# Generated by Django 4.1 on 2023-10-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0016_alter_textsection_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumesection',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
