# Generated by Django 4.1 on 2023-10-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0018_alter_resumesection_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsection',
            name='text',
        ),
        migrations.RemoveField(
            model_name='resumesection',
            name='text',
        ),
        migrations.RemoveField(
            model_name='textsection',
            name='text',
        ),
        migrations.AddField(
            model_name='section',
            name='text',
            field=models.TextField(default='None', max_length=1000),
            preserve_default=False,
        ),
    ]
