# Generated by Django 4.1 on 2023-10-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0022_rename_is_flag_enabled_sitesettings_push_static'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='push_static',
            new_name='is_flag_enabled',
        ),
    ]
