# Generated by Django 4.1 on 2023-10-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0023_rename_push_static_sitesettings_is_flag_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='is_flag_enabled',
            new_name='push_static',
        ),
    ]
