# Generated by Django 4.1 on 2023-11-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0024_rename_is_flag_enabled_sitesettings_push_static'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeentry',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='resumeentry',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
