# Generated by Django 4.1 on 2023-11-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0026_projectsection_projectentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeentry',
            name='link',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
