# Generated by Django 4.1 on 2023-11-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0027_alter_resumeentry_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeentry',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
