# Generated by Django 4.1 on 2023-11-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0029_resumeentry_link_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectentry',
            name='link_text',
            field=models.CharField(default='text', max_length=200),
            preserve_default=False,
        ),
    ]
