# Generated by Django 4.1 on 2023-11-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0030_projectentry_link_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
